-- Generated by scripts/hypr2lua.
-- Source: omarchy-hex-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(ff00f6)", "rgb(b300ad)", "rgb(b300ad)", "rgb(b300ad)", "rgb(b9b1bc)", "rgb(b300ad)", "rgb(b300ad)", "rgb(b300ad)", "rgb(ff00f6)" },
  angle = 20,
}
local inactiveBorderColor = {
  colors = { "rgb(7f7094)", "rgb(7f7094)", "rgb(7f7094)", "rgb(241b30)", "rgb(241b30)" },
  angle = 30,
}

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_out = 12,
    gaps_in = 8,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 42,
    rounding_power = 1,
    shadow = {
      enabled = true,
      range = 26,
      render_power = 4,
      offset = "2 2",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("hexEase", { type = "bezier", points = { { 0.2, 0.8 }, { 0.2, 1.0 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 6,
  bezier = "hexEase",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 6,
  bezier = "hexEase",
  style = "slide",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 8,
  bezier = "hexEase",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 5,
  bezier = "hexEase",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 6,
  bezier = "hexEase",
  style = "slide",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 6,
  bezier = "hexEase",
  style = "slide",
})
